### PR TITLE
fix: multiple attribute select

### PR DESCRIPTION
**Pull request by doproiescu-plenty**
## Why:

Closes: #ID

## Checklist before requesting a review
- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by rbedeoan-plenty** [comment]
Screenshot 2023-09-22 at 15 28 25
havee some console errors here

**Review by rbedeoan-plenty — DISMISSED** [review]
solve console errors(linting stuf) and you can merge

**Review by Tim-M-S — COMMENTED** [review]
If you select the 1. and 3. attribute and then click on "Please select" in the first attribute, it deselects both the 1. and 3. attribute. It should only deselect the one clicked

**Review by rbedeoan-plenty — APPROVED** [review]
i please select behaviour is ok,approved

**Pull request merged**
